import Head from 'next/head'
import { Gluten } from '@next/font/google'
import Header from '../components/Header'
const gluten = Gluten({ subsets: ['latin'] })

export default function Home () {
  return (
    <div className={gluten.className}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>Get started by editing&nbsp;</main>
    </div>
  )
}
