import Head from 'next/head'
import Boxes from '../components/Boxes'

// import { Gluten } from '@next/font/google'
// const gluten = Gluten({ subsets: ['latin'] })

export default function Home () {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Boxes />
      </main>
    </div>
  )
}
